import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./home.module.css";
import Footer from "@/components/footer/Footer";
import CustomNav from "@/components/Nadvar/Nadvar2";
import "./globals.css";
import { ProductProvider } from "@/context/produc";
import { CarritoProvider } from "@/context/carrito";
import { UserProvider } from "@/context/userContex";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Apple Zone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <div className="min-h-screen flex flex-col">
          <CarritoProvider>
            <UserProvider>
              <ProductProvider>
                <CustomNav />
                <main className="flex flex-grow justify-center ml-5 mr-5">
                  {children}
                </main>
                <footer>
                  <Footer />
                </footer>
              </ProductProvider>
            </UserProvider>
          </CarritoProvider>
        </div>
      </body>
    </html>
  );
}
